pipeline {

  agent {
    docker {
      image 'maven:latest'
    }
  }

  stages {
    stage('build') {
      steps {
        dir('basit-uygulama'){
          sh 'mvn -B -DskipTests clean package'
        }
      }
    }
    stage('test'){
      steps {
        dir('basit-uygulama'){
          sh 'mvn test'
        }
      }
      post {
        dir('basit-uygulama'){
          always{
            junit 'target/surefire-reports/*.xml'
          }
        }
      }
    }
    stage('Deliver'){
      steps {
        dir('basit-uygulama'){
          sh './deliver.sh'
        }
      }
    }
  }

}
