pipeline {

  agent {
    docker {
      image 'maven:latest'
    }
  }


  stages {
    stage('build') {
      steps {
        dir('basit-uygulama'){
          sh 'mvn -B -DskipTests clean package'
        }
      }
    }
    stage('Deliver'){
      steps {
        sh 'echo deliver.sh'
      }
    }
  }

}
